channels:
  - main
dependencies:
  - python=3.12
  - numba::llvmlite=0.46.*
  - sklam::mlir-python-bindings=21.*
  - pytest
  - networkx
  - numpy
  - mypy
  # egglog doesn't install this
  - cloudpickle 
  - pip
  - pip:
    - egglog ==12
    - numba_rvsdg
platforms:
  - osx-arm64
  - linux-64
  